(function(){
'use strict';
const biology=[
 {id:'B1',title:'Cells: eukaryotes and prokaryotes',summary:'Compare animal, plant and bacterial cells and link each sub-cellular structure to its function.',must:['Eukaryotic genetic material is enclosed in a nucleus; prokaryotic genetic material is not.','Mitochondria: aerobic respiration. Ribosomes: protein synthesis.','Plant cells also have a cellulose cell wall, chloroplasts and a permanent vacuole.','Bacteria have circular DNA and may contain plasmids.'],mistakes:['Bacteria do have DNA.','The cell membrane, not the cell wall, controls movement into and out of the cell.']},
 {id:'B2',title:'Cell specialisation and differentiation',summary:'Explain how differentiated cells develop structures suited to their functions.',must:['Differentiation is the process by which a cell becomes specialised.','Link adaptation → effect → benefit.','Know examples such as sperm, nerve, muscle, root hair, xylem and phloem cells.'],mistakes:['Do not write vague claims such as “shaped for its job”; name the adaptation.']},
 {id:'B3',title:'Microscopy and magnification',summary:'Use microscopes, biological drawing rules and magnification calculations.',must:['magnification = image size ÷ real size','1 mm = 1000 μm; 1 μm = 1000 nm.','Resolution is the ability to distinguish two close points as separate.'],practical:'Required Practical 1: prepare a thin specimen, add stain if needed, lower a coverslip carefully, begin on low power, focus, then draw and label what is observed.',mistakes:['Convert units before calculating.','Higher magnification is not the same as higher resolution.']},
 {id:'B4',title:'Culturing microorganisms and aseptic technique',summary:'Understand binary fission, uncontaminated cultures and safe school-laboratory technique.',must:['Sterilise culture media/equipment and the inoculating loop.','Open the Petri-dish lid as little as possible.','Tape at a few points, invert and incubate at no more than 25°C in school.'],practical:'Required Practical 2 focus: aseptic technique and streak plating. Re-sterilising the loop between streak regions progressively dilutes cells and helps produce isolated colonies.',extension:'Antibiotic/antiseptic inhibition-zone work is AQA-linked knowledge; it is not treated as the default TGS Year 9 core unless taught.'},
 {id:'B5',title:'Chromosomes, the cell cycle and mitosis',summary:'Describe the cell cycle and explain why mitosis is needed.',must:['growth and organelles increase → DNA replicates → mitosis → cytoplasm/membrane divide','Mitosis produces two genetically identical daughter cells.','Uses include growth, repair, replacement and some asexual reproduction.'],mistakes:['DNA replication occurs before mitosis.','Detailed meiosis is not the core focus at this point.']},
 {id:'B6',title:'Stem cells',summary:'Compare embryonic, adult and plant meristem stem cells and evaluate uses and risks.',must:['A stem cell is undifferentiated and can divide and differentiate.','Embryonic stem cells can form a wide range of human cell types; adult stem cells are more limited.','Plant meristems can keep differentiating throughout life.'],mistakes:['Evaluation needs benefits, risks/ethical issues and a justified conclusion.']},
 {id:'B7',title:'DNA and the genome',summary:'Connect cells, nuclei, chromosomes, DNA and genes and recognise the basic double-helix structure.',must:['cell → nucleus → chromosome → DNA → gene','DNA is a polymer of nucleotides; each nucleotide contains sugar, phosphate and a base.','The genome is the entire genetic material of an organism.'],extension:'Complementary base pairing and full protein-synthesis detail are later/AQA depth unless explicitly taught.',mistakes:['A gene is a section of DNA, not an organelle.']},
 {id:'B8',title:'Diffusion',summary:'Explain net particle movement down a concentration gradient and the factors affecting rate.',must:['Diffusion is net movement from higher to lower concentration.','A larger gradient, higher temperature and larger surface area increase diffusion rate; shorter distance improves exchange.','Diffusion does not require energy from respiration.'],mistakes:['Individual particles move randomly; the net movement is down the gradient.']},
 {id:'B9',title:'Osmosis',summary:'Explain water movement through a partially permeable membrane and interpret plant-tissue data.',must:['Osmosis is the diffusion of water from a dilute solution to a concentrated solution through a partially permeable membrane.','percentage change = (final mass − initial mass) ÷ initial mass × 100'],practical:'Required Practical 3: measure equal plant-tissue samples before and after known solution concentrations, blot consistently, calculate percentage change and plot concentration against change.',mistakes:['Osmosis is water only and requires a partially permeable membrane.']},
 {id:'B10',title:'Active transport',summary:'Explain movement against a concentration gradient using energy transferred by respiration.',must:['Active transport moves substances from a more dilute to a more concentrated region.','Examples: mineral-ion uptake by root hair cells and glucose absorption in the small intestine.'],mistakes:['Active transport is not the name for water movement; water movement across a partially permeable membrane is osmosis.']},
 {id:'B11',title:'Aerobic and anaerobic respiration',summary:'Distinguish respiration from breathing and learn the key word equations.',must:['aerobic: glucose + oxygen → carbon dioxide + water','muscles anaerobic: glucose → lactic acid','yeast/plants anaerobic: glucose → ethanol + carbon dioxide','Respiration is an exothermic chemical process in living cells.'],mistakes:['Plants respire as well as photosynthesise.']},
 {id:'B12',title:'Response to exercise',summary:'Link increased energy demand to breathing, circulation and lactic acid.',must:['Exercise raises heart rate, breathing rate and breathing depth.','More oxygen and glucose are delivered to muscles and carbon dioxide is removed faster.','Lactic acid can accumulate if oxygen supply cannot meet demand.']},
 {id:'B13',title:'Metabolism',summary:'Use the biological definition of metabolism and recognise examples of metabolic reactions.',must:['Metabolism is the sum of all the chemical reactions in a cell or body.','Respiration transfers energy that can drive other metabolic reactions.'],mistakes:['Metabolism does not only mean how quickly someone burns calories.']},
 {id:'B14',title:'Photosynthesis',summary:'Learn the equations and explain why photosynthesis is endothermic.',must:['carbon dioxide + water → glucose + oxygen','6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂','Light energy is absorbed by chlorophyll in chloroplasts.'],mistakes:['Plants make glucose; they do not obtain “food” from soil.']},
 {id:'B15',title:'Rate of photosynthesis',summary:'Explain limiting factors and analyse a light-intensity investigation.',must:['Limiting factors include light intensity, carbon dioxide concentration, temperature and chlorophyll.','A limiting factor is the factor in shortest supply for the current conditions.'],practical:'Required Practical 6: vary light intensity or lamp distance, measure oxygen production over time, control temperature/CO₂/plant material/time, repeat and calculate a mean.',extension:'Using 1/d² as an approximation for light intensity and detailed interactions/economics are marked HT/AQA depth unless explicitly taught.'},
 {id:'B16',title:'Uses of glucose',summary:'Trace the main uses of glucose made in photosynthesis.',must:['Glucose is used in respiration.','It can be converted to starch, cellulose and lipids/oils.','With nitrate ions it can be used to make amino acids and then proteins.']}
];

const chemistry=[
 {id:'C1',title:'Development of the Periodic Table',summary:'Compare Newlands and Mendeleev and explain how evidence improved the model.',must:['Mendeleev prioritised chemical properties, left gaps and made testable predictions.','Later discoveries matching predictions supported his arrangement.'],mistakes:['Do not say Mendeleev knew all the elements; leaving gaps was a strength.']},
 {id:'C2',title:'Elements, compounds and mixtures',summary:'Distinguish the three using particles, bonding and separation.',must:['Element: one type of atom.','Compound: elements chemically bonded in fixed proportions.','Mixture: substances together but not chemically bonded.'],mistakes:['A compound is not simply two substances mixed together.']},
 {id:'C3',title:'Separation techniques',summary:'Choose filtration, crystallisation, evaporation or distillation from physical properties.',must:['Filtration separates an insoluble solid from a liquid.','Crystallisation can obtain a dissolved solid.','Distillation uses differences in boiling point.']},
 {id:'C4',title:'Chromatography',summary:'Use chromatography to separate dissolved substances and interpret chromatograms.',must:['Rf = distance travelled by substance ÷ distance travelled by solvent front.','Use the same baseline and solvent conditions when comparing results.'],practical:'Mark the baseline in pencil, place samples above the solvent level and measure distances from the baseline.'},
 {id:'C5',title:'Atomic structure and isotopes',summary:'Use proton, neutron and electron properties to calculate atomic and mass numbers.',must:['Atomic number = number of protons.','Mass number = protons + neutrons.','Isotopes have the same proton number but different neutron numbers.','For the first 20 elements, use the introductory shell model.'],mistakes:['Changing proton number changes the element.']},
 {id:'C6',title:'Development of the atomic model',summary:'Link new experimental evidence to changes in scientific models.',must:['sphere → plum pudding → nuclear model → Bohr shells → protons/neutrons','Alpha-scattering evidence supported a small dense positive nucleus and mostly empty space.','Peer review lets other scientists scrutinise methods, data and conclusions.']},
 {id:'C7',title:'Formulae, conservation and balancing',summary:'Interpret formulae and balance symbol equations without changing substances.',must:['Mass is conserved in a closed system because atoms are rearranged, not created or destroyed.','Balance equations by changing coefficients, not formula subscripts.'],mistakes:['Changing H₂O to H₂O₂ does not “balance” water; it creates a different substance.']},
 {id:'C8',title:'Crude oil, fractional distillation and alkanes',summary:'Explain how crude oil fractions are separated and recall alkane patterns.',must:['A hydrocarbon contains carbon and hydrogen only.','Alkanes are saturated and follow CₙH₂ₙ₊₂.','First four: methane, ethane, propane, butane.','Longer chains generally have higher boiling points and viscosity and lower volatility/flammability.']},
 {id:'C9',title:'Combustion and fossil-fuel pollution',summary:'Distinguish complete and incomplete combustion and explain key pollutants.',must:['Complete combustion of a hydrocarbon forms carbon dioxide and water.','Limited oxygen can produce carbon monoxide and/or soot.','Know impacts of sulfur dioxide, nitrogen oxides, particulates and carbon dioxide.']},
 {id:'C10',title:'Cracking and alkenes',summary:'Explain why long hydrocarbons are cracked and recognise alkene chemistry.',must:['Cracking makes shorter alkanes and alkenes.','Alkenes are unsaturated, contain C=C and follow CₙH₂ₙ.','Bromine water changes from orange to colourless with an alkene.']},
 {id:'C11',title:'Reactions of alkenes',summary:'Describe addition reactions across the C=C bond.',must:['Hydrogenation: alkene + hydrogen → alkane.','Hydration: alkene + steam → alcohol.','Halogenation adds halogen atoms across the double bond.']},
 {id:'C12',title:'Addition polymerisation',summary:'Relate alkene monomers to long-chain addition polymers.',must:['The C=C bond opens during addition polymerisation.','Many alkene monomers join to form a long saturated carbon chain.']},
 {id:'C13',title:'Collision theory and reaction rates',summary:'Explain how concentration, pressure, surface area, temperature and catalysts affect rate.',must:['Particles must collide with enough energy for a successful reaction.','Higher temperature increases kinetic energy and the fraction of collisions above activation energy.','A catalyst provides an alternative pathway with lower activation energy and is not used up overall.']},
 {id:'C14',title:'Rates practical and graph analysis',summary:'Plan, analyse and evaluate a rate experiment.',must:['Steeper product-volume gradient means faster rate.','A plateau occurs when the limiting reactant is used up.','Instantaneous rate can be estimated from a tangent gradient.'],practical:'Required Practical 5: investigate concentration using a gas-volume method and/or a colour/turbidity endpoint; control relevant variables and repeat where useful.'},
 {id:'C15',title:"Earth's present atmosphere",summary:'Recall the approximate modern atmospheric composition.',must:['About 78–80% nitrogen.','About 20–21% oxygen.','Small amounts of argon/noble gases, carbon dioxide and water vapour.']},
 {id:'C16',title:"Earth's early atmosphere",summary:'Explain how scientific evidence supports models of atmospheric change.',must:['An early model has a CO₂-rich atmosphere from volcanic activity with little/no oxygen.','Cooling formed oceans; CO₂ decreased through oceans, carbonate rocks, fossil fuels and photosynthesis.','Oxygen later rose through photosynthesis.']},
 {id:'C17',title:'Greenhouse gases and climate change',summary:'Explain the greenhouse effect, human influences, carbon footprints and evidence.',must:['Important greenhouse gases include carbon dioxide, methane and water vapour.','Greenhouse gases absorb and re-emit infrared radiation.','Human activities can increase CO₂ and methane concentrations.','A carbon footprint covers greenhouse-gas emissions across a life cycle.'],mistakes:['The greenhouse effect is not ozone depletion.','Uncertainty in exact predictions does not mean there is no evidence.']}
];

const physics=[
 {id:'P1',title:'Particle model of matter',summary:'Use particle arrangement and motion to explain solids, liquids and gases.',must:['Solid particles are close and vibrate about fixed positions.','Liquid particles are close but can move past each other.','Gas particles are far apart and move rapidly in random directions.','Temperature relates to average particle kinetic energy.'],mistakes:['Particles do not simply expand when a substance is heated.']},
 {id:'P2',title:'Density',summary:'Use density calculations and methods for regular solids, irregular solids and liquids.',must:['ρ = m ÷ V','Use consistent units; SI density is kg/m³.'],practical:'Required Practical 5: measure mass and volume appropriately; use water displacement for irregular solids and subtract container mass for liquids.'},
 {id:'P3',title:'Internal energy and heating',summary:'Distinguish temperature from total internal energy.',must:['Internal energy is the total kinetic and potential energy of all particles in a system.','Heating may raise particle kinetic energy/temperature or change particle potential energy during a state change.'],mistakes:['Internal energy is not simply “heat inside an object”.']},
 {id:'P4',title:'Conduction and thermal insulation',summary:'Explain energy transfer in solids and evaluate insulation.',must:['Vibrating particles transfer energy to neighbours.','Free electrons help metals conduct thermal energy rapidly.','Trapped gases can reduce conduction and bulk movement.'],practical:'Required Practical 2: compare insulating materials under controlled conditions using equal starting conditions, timing and measurements.'},
 {id:'P5',title:'Infrared radiation and surfaces',summary:'Compare absorption, emission and reflection of infrared radiation.',must:['Hotter objects generally emit infrared at a greater rate.','Dark matt surfaces are good absorbers/emitters; light shiny surfaces are poorer absorbers/emitters and better reflectors.'],practical:'A Leslie cube demonstration compares infrared emitted by surfaces with different finishes.',extension:'Do not relabel the TGS classroom Leslie-cube demonstration as a separate Year 9 required practical unless the teacher does so.'},
 {id:'P6',title:'Specific heat capacity',summary:'Use ΔE = mcΔθ and understand the required practical.',must:['Specific heat capacity is the energy needed to raise 1 kg by 1°C.','ΔE = m c Δθ','Use temperature change, not final temperature.'],practical:'Required Practical 1: measure block mass, energy supplied and temperature rise, reduce heat loss and calculate c; repeated readings/graphs can strengthen evidence.'},
 {id:'P7',title:'Changes of state',summary:'Explain melting, freezing, boiling/evaporation and condensation using particles and heating curves.',must:['Changes of state are physical and reversible.','During a phase change of a pure substance at constant pressure, energy can transfer while temperature stays constant.','Flat graph sections show state changes.']},
 {id:'P8',title:'Power and energy',summary:'Use power to describe the rate of energy transfer or work done.',must:['P = E ÷ t','P = W ÷ t','1 watt = 1 joule per second.'],mistakes:['Power is a rate; it is not the same quantity as energy.']},
 {id:'P9',title:'Specific latent heat',summary:'Calculate energy for a change of state at constant temperature.',must:['E = mL','Fusion is solid ↔ liquid; vaporisation is liquid ↔ gas.','Specific latent heat changes state without changing temperature.'],mistakes:['Do not use ΔE=mcΔθ for the flat phase-change section.']},
 {id:'P10',title:'Evaporation',summary:'Use particle energy to explain evaporation and cooling.',must:['Evaporation occurs at a liquid surface and can occur below boiling point.','Higher-energy particles are more likely to escape, lowering the average kinetic energy of those left.','Higher temperature, larger surface area, greater air movement and lower humidity increase evaporation.']},
 {id:'P11',title:"Gas pressure and Boyle's law",summary:'Relate gas pressure to wall collisions and use pV = constant.',must:['For fixed mass at constant temperature: pV = constant, so p₁V₁ = p₂V₂.','Reducing volume increases collision frequency with container walls.'],practical:'TGS includes a pressure–volume experiment showing the inverse relationship at constant temperature.'},
 {id:'P12',title:'Gas pressure and temperature',summary:'Explain why pressure rises with temperature at constant volume.',must:['Higher temperature means greater average particle kinetic energy.','Particles collide with walls more frequently and with greater momentum change.'],mistakes:['Pressure–volume work assumes constant temperature; this pressure–temperature explanation assumes constant volume.']},
 {id:'P13',title:'Energy stores and pathways',summary:'Describe energy stores, transfers, conservation and dissipation.',must:['Stores include kinetic, thermal/internal, gravitational, elastic, chemical, magnetic, electrostatic and nuclear.','Transfers can be mechanical, electrical, by heating or by radiation.','Energy is conserved but may become dissipated.']},
 {id:'P14',title:'Kinetic energy',summary:'Calculate and reason with kinetic energy.',must:['Eₖ = ½mv²','Doubling speed makes kinetic energy four times larger if mass is unchanged.'],mistakes:['Square the speed, not the mass.']},
 {id:'P15',title:'Gravitational potential energy',summary:'Calculate GPE and explain transfers between GPE, kinetic and dissipated stores.',must:['Eₚ = mgh','As an object falls, gravitational energy can transfer to kinetic energy; resistance may dissipate some energy.']},
 {id:'P16',title:"Springs and Hooke's law",summary:'Use force–extension relationships and distinguish proportional and elastic limits.',must:['F = ke below the limit of proportionality.','extension = stretched length − original length','Limit of proportionality and elastic limit are different ideas.'],practical:'Required Practical 6: add known loads, measure extension, repeat/check unloading and plot force against extension.'},
 {id:'P17',title:'Elastic potential energy',summary:'Calculate energy stored in a spring and interpret the graph area.',must:['Eₑ = ½ke² below the limit of proportionality.','For a linear force–extension graph, area under the graph gives work done/energy transferred.'],mistakes:['Extension must be in metres for standard SI calculations.']},
 {id:'P18',title:'Efficiency',summary:'Calculate efficiency and explain how unwanted transfers can be reduced.',must:['efficiency = useful energy output ÷ total energy input','or useful power output ÷ total power input','Efficiency is between 0 and 1, or 0% and 100%.','Reduce specific unwanted transfers through design, insulation or reduced friction where relevant.']}
];

const packs={
 biology:{subject:'Biology',accent:'biology',topics:biology},
 chemistry:{subject:'Chemistry',accent:'chemistry',topics:chemistry},
 physics:{subject:'Physics',accent:'physics',topics:physics}
};
window.ScholarScience=Object.freeze({
 packs,
 get(subject){return packs[subject]||null},
 topic(subject,id){return packs[subject]?.topics.find(t=>t.id===id)||null}
});
})();